# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - drawer_planning_group_controller

  drawer_planning_group_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - drawer_1_joint
      - drawer_2_joint
      - drawer_3_joint
      - drawer_4_joint
      - drawer_5_joint