services:
  backend:
    build:
      context: ../../src/web/backend
      dockerfile: Dockerfile
    image: backend:fast_api
    ports:
      - "8000:8000"
    volumes:
      - ./backend/:/workspace/:cached
      - ../../src/web/backend:/workspace/src/:cached
    command: /bin/sh -c "while sleep 1000; do :; done"

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB= robast
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  
    
volumes:
  db:
    driver: local