version: '3.9'

services:
  backend:
    build:
      context: ../../src/web/backend
      dockerfile: Dockerfile
    image: backend:fast_api
    ports:
      - "8000:8000"
    volumes:
      - ./backend/:/workspace/:cached
      - ../../src/web/backend:/workspace/src/:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    # command: /bin/sh -c "python /workspace/src/main.py"