version: '3'
services:
  backend:
    build:
      context: ../../src/web/backend
      dockerfile: Dockerfile
    image: backend:fast_api
    expose:
      - "8000:8000"
    volumes:
      - ./backend/:/workspace/:cached
      - ../../src/web/backend:/workspace/src/:cached
    depends_on:
      - db  
    command: /bin/sh -c "while sleep 1000; do :; done"
    network_mode: "host" 

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=robast
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
   

volumes:
  db:
    driver: local