#goal
# no specific goal needed, because calling this action has only one possible result: Opening the drawer
---
#result
bool success  # indicates whether closing of the drawer was successfull after opening it
---
#feedback
bool is_drawer_open  # information of the sensor data about the status of the electrical locker