drawer_nfc_tree_initiator:
  ros__parameters:
    plugins:
      - drawer_change_state_request_action_bt_node
      - change_led_action_bt_node
      - open_drawer_action_bt_node
      - drawer_status_condition_bt_node
      - nfc_to_drawer_action_bt_node
      - base_error_decorator_node
    bt_path: "/workspace/install/drawer_sm/trees/trees/drawer_nfc_bt.xml"
