robot_tree_initiator:
  ros__parameters:
    plugins:
      - base_error_decorator_node
      - initialize_led_vector_action_bt_node
      - publish_led_action_bt_node
      - partial_colorize_leds_action_bt_node
      - get_blackboard_value_action_bt_node
      - bool_topic_condition_node
      - led_changed_condition_node
      - is_robot_charging_condition_node
      - import_environment_led_color_action_bt_node
      - evaluate_drive_direction_action_bt_node
      - publish_state_feedback_action_bt_node
      - set_default_led_color_action_bt_node
    bt_path: "/workspace/src/statemachine/drawer_sm/trees/Robo_base.xml"
    trigger_topic: "trigger_base_tree"
    main_tree: "BehaviorTree"
    tree_tick_time: 200
