camera_model: 'OAK-D'
tf_prefix: 'oak_s'
base_frame: 'oak-d_frame'
parent_frame: 'robot/base_link'

cam_pos_x: '0.317'
cam_pos_y: '-0.197'
cam_pos_z: '1.3044'
cam_roll: '0.0'
cam_pitch: '0.0'
cam_yaw: '0.0'

mode: 'depth'
lrcheck: true
extended: false
subpixel: true
confidence: 120
LRchecktresh: 5
monoResolution: '720p'