#goal
nav_msgs/Path path  # path to the final goal pose
geometry_msgs/PoseStamped pose  # the final pose
string controller_id
---
#result
geometry_msgs/PoseStamped interim_pose
builtin_interfaces/Duration planning_time
---
#feedback
std_msgs/Empty feedback