# RMF door parameters

### template ###
door:
  name: "example_door"
  api_endpoint: "http://127.0.0.1:8888/"
  door_id: "example_door_id"
  door_signal_period_in_sec: 3.0
  door_close_feature: True

door_subscriber:
  topic_name: "adapter_door_requests"

door_publisher:
  topic_name: "door_states"
  door_state_publish_period_in_sec: 1.0
