# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz
    # use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    stretch_base_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    drawer_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    streaming_controller:
      type: position_controllers/JointGroupPositionController

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    wheel_separation: 0.5032
    #wheels_per_side: 1  # actually 2, but both are controlled by 1 signal
    wheel_radius: 0.0762

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_footprint
    pose_covariance_diagonal : [0.0000001, 0.0000001, 0.0000001, 0.0000001, 0.0000001, 0.0000001]
    twist_covariance_diagonal: [0.0000000001, 0.0000000001, 0.0000000001, 0.0000000001, 0.0000000001, 0.0000000001]

    open_loop: true
    # DISABLE enable_odom_tf, when using robot_localization
    enable_odom_tf: false 

    cmd_vel_timeout: 0.5
    #publish_limited_velocity: true
    use_stamped_vel: false
    #velocity_rolling_window_size: 10

    # Preserve turning radius when limiting speed/acceleration/jerk
    preserve_turning_radius: true

    # Publish limited velocity
    publish_cmd: true

    # Publish wheel data
    publish_wheel_data: true

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 1.0
    linear.x.min_velocity: -1.0
    linear.x.max_acceleration: 1.0
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 1.0
    angular.z.min_velocity: -1.0
    angular.z.max_acceleration: 1.0
    angular.z.min_acceleration: -1.0
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0

joint_trajectory_controller:
  ros__parameters:
    joints:
      - door_opening_mechanism_joint_y_axis_slide
      - door_opening_mechanism_joint_x_axis_slide
      - door_opening_mechanism_joint_rotating_arm
      - door_opening_mechanism_joint_freely_rotating_hook
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
    command_joints:
      - door_opening_mechanism_joint_y_axis_slide
      - door_opening_mechanism_joint_x_axis_slide
      - door_opening_mechanism_joint_rotating_arm
      - door_opening_mechanism_joint_freely_rotating_hook

    state_publish_rate: 50.0 # Defaults to 50
    action_monitor_rate: 20.0 # Defaults to 20

    allow_partial_joints_goal: false # Defaults to false
    open_loop_control: true
    allow_integration_in_goal_trajectories: true
    allow_nonzero_velocity_at_trajectory_end: true
    interpolation_method: splines
    gains:
      door_opening_mechanism_joint_y_axis_slide:
        p: 10.0
        i: 1.0
        d: 0.1
        ff_velocity_scale: 1.0
      door_opening_mechanism_joint_x_axis_slide:
        p: 10.0
        i: 1.0
        d: 0.1
        ff_velocity_scale: 1.0
      door_opening_mechanism_joint_rotating_arm:
        p: 10.0
        i: 1.0
        d: 0.1
        ff_velocity_scale: 1.0
      door_opening_mechanism_joint_freely_rotating_hook:
        p: 10.0
        i: 1.0
        d: 0.1
        ff_velocity_scale: 1.0

stretch_base_controller:
  ros__parameters:
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
    allow_partial_joints_goal: true
    open_loop_control: true # disables PID
    allow_integration_in_goal_trajectories: true
    joints:
      - position/x
      - position/y
      - position/theta
    command_joints:
      - diff_drive_controller/x
      - diff_drive_controller/y
      - diff_drive_controller/theta

drawer_joint_trajectory_controller:
  ros__parameters:
    joints:
      - drawer_1_joint
      - drawer_2_joint
      - drawer_3_joint
      - drawer_4_joint
      - drawer_5_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

streaming_controller:
  ros__parameters:
    joints:
      - door_opening_mechanism_joint_y_axis_slide
      - door_opening_mechanism_joint_x_axis_slide
      - door_opening_mechanism_joint_rotating_arm
      - door_opening_mechanism_joint_freely_rotating_hook
      - position_joint