version: '3.9'

services:
  simulation:
    image: ghcr.io/robast-gmbh/monorepo/simulation:devel
    environment:
      - ROS_DOMAIN_ID=1
      - is_simulation=True
      - config_directory=config_simulation
      - robot_name=rb_theron
      - init_x=-2.0
      - init_y=0.0
      - init_z=0.0
      - init_yaw=3.14
      - robot=rb_theron
      - prefix=
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    volumes:
      - ./simulation/:/workspace/:cached
      - ../../src/ros2/simulation:/workspace/src/simulation:cached
      - ../../src/ros2/robot_description:/workspace/src/robot_description:cached
      - ../../src/ros2/communication_interfaces:/workspace/src/communication_interfaces:cached
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../../src/ros2/dds_configs:/workspace/dds_configs:cached
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
#    network_mode: "host"
    command: /bin/sh -c "while sleep 1000; do :; done"
    
  navigation:
    image: ghcr.io/robast-gmbh/monorepo/navigation:devel
    environment:
      - ROS_DOMAIN_ID=1
      - is_simulation=True
      - config_directory=config_simulation
      - robot_name=rb_theron
      - init_x=0.0
      - init_y=0.0
      - init_z=0.0
      - init_yaw=3.14
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    volumes:
      - ./navigation/:/workspace/:cached
      - ../../src/ros2/navigation:/workspace/src/navigation:cached
      - ../../src/ros2/communication_interfaces:/workspace/src/communication_interfaces:cached
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../../src/ros2/dds_configs:/workspace/dds_configs:cached
    command: /bin/sh -c "while sleep 1000; do :; done"

  moveit_mtc:
    image: ghcr.io/robast-gmbh/monorepo/moveit_mtc:devel
    environment:
      - ROS_DOMAIN_ID=1
      - is_simulation=True
      - config_directory=config_simulation
      - robot_name=rb_theron
      - robot=rb_theron
      - prefix=
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    volumes:
      - ./moveit_mtc/:/workspace/:cached
      - ../../src/ros2/robot_description:/workspace/src/robot_description:cached
      - ../../src/ros2/moveit:/workspace/src/moveit:cached
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../../src/ros2/dds_configs:/workspace/dds_configs:cached
#    network_mode: "host"
    command: /bin/sh -c "while sleep 1000; do :; done"

