rooms:
  1:
    center point:
      x: 5.5
      y: 13.7
  2:
    center point:
      x: 13.5
      y: 13.7
  3:
    center point:
      x: 18.8
      y: 13.8
  4:
    center point:
      x: 24.8
      y: 13.8
  5:
    center point:
      x: 30.0
      y: 14.0
  6:
    center point:
      x: 11.0
      y: 8.6
  7:
    center point:
      x: 29.2
      y: 8.7
  8:
    center point:
      x: 14.1
      y: 3.3
  9:
    center point:
      x: 24.5
      y: 3.3
  # Now those rooms begin, that are harder to access due to the small door
  # 10:
  #   center point:
  #     x: 2.8
  #     y: 9.8
  # 11:
  #   center point:
  #     x: 20.0
  #     y: 3.3
  # 12:
  #   center point:
  #     x: 8.7
  #     y: 3.3
