modules:
  - module_id: 1
    drawer_id: 0
    pos: 1
    size: 1
    type: "manual_drawer"
  - module_id: 2
    drawer_id: 0
    pos: 2
    size: 1
    type: "electric_drawer"
  - module_id: 3
    drawer_id: 0
    pos: 3
    size: 1 
    type: "manual_drawer"
  - module_id: 4
    drawer_id: 0
    pos: 4
    size: 2
    type: "manual_drawer"
  - module_id: 5
    drawer_id: 0
    pos: 5
    size: 3
    type: "manual_drawer"