controller_manager:
  ros__parameters:
    update_rate: 500  # Hz
    door_opening_mechanism_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    door_opening_mechanism_position_controller:
      type: position_controllers/JointGroupPositionController

door_opening_mechanism_controller:
  ros__parameters:
    joints:
      - door_opening_mechanism_joint_y_axis_slide
      - door_opening_mechanism_joint_x_axis_slide
      - door_opening_mechanism_joint_tilting_hook
      - position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

door_opening_mechanism_position_controller:
  ros__parameters:
    joints:
      - door_opening_mechanism_joint_y_axis_slide
      - door_opening_mechanism_joint_x_axis_slide
      - door_opening_mechanism_joint_tilting_hook