type: robot_local_control_components/CartographerLocalizationComponent
##type: XXXLocalizationComponent # not used yet
##publish_frequency: 2  # hertz, not used yet
##update_frequency: 2   # hertz, not used yet

desired_freq: 2.0
use_frame_mapping: false
frame_mapping_init_pose_service: frame_mapping/init_pose

# amcl_topic is reffered to the global namespace (unless absolute path is used)
# example: amcl_pose will be resolved to /robot/amcl_pose or /robot_a/amcl_pose
cartographer_topic: tracked_pose
cartographer_initialpose_topic: initialpose
cartographer_constraint_matches_topic: constraint_matches

manual_init_required: false
frame_mapping_init_required: false
cartographer_match_constraint_required: true
check_all_requirements: false # true: check all _required params. false: check just one of them
