<?xml version="1.0"?>
<robot name="drawer" xmlns:xacro="http://www.ros.org/wiki/xacro">

<xacro:macro name="box_inertia_robot" params="m x y z">
	<inertia  ixx="${m*(y*y+z*z)/12}" ixy = "0" ixz = "0"
			iyy="${m*(x*x+z*z)/12}" iyz = "0"
			izz="${m*(x*x+z*z)/12}" />
</xacro:macro>

<xacro:property name="drawer_size_x" value="0.45" />
<xacro:property name="drawer_size_y" value="0.358" />
<xacro:property name="drawer_size_z" value="0.08" />
<xacro:property name="drawer_mass" value="1.5" />

<xacro:property name="drawer_offset_x" value="0.0" />
<xacro:property name="drawer_offset_y" value="0.0" />
<xacro:property name="drawer_offset_z" value="0.0" />


<xacro:macro name="drawer" params="prefix parent *origin">
        <link name="${prefix}_drawer">
                <inertial>
                        <mass value="${drawer_mass}" />
                        <origin xyz="${drawer_offset_x} ${drawer_offset_y} ${drawer_offset_z}" />
                        <xacro:box_inertia_robot m="${drawer_mass}" x="${drawer_size_x}" y="${drawer_size_y}" z="${drawer_size_z}"/>
                </inertial>
                <visual>
                        <!-- visual origin is defined w.r.t. link local coordinate system -->
                        <origin xyz="${drawer_offset_x} ${drawer_offset_y} ${drawer_offset_z}" rpy="0 0 0" />
                        <geometry>
                        <box size="${drawer_size_x} ${drawer_size_y} ${drawer_size_z}" />
                        </geometry>
                </visual>
                <collision>
                        <!-- collision origin is defined w.r.t. link local coordinate system -->
                        <origin xyz="${drawer_offset_x} ${drawer_offset_y} ${drawer_offset_z}" rpy="0 0 0 " />
                        <geometry>
                        <box size="${drawer_size_x} ${drawer_size_y} ${drawer_size_z}" />
                        </geometry>
                </collision>
        </link>

        <gazebo reference="${prefix}_drawer">
                <material>Gazebo/White</material>
                <turnGravityOff>false</turnGravityOff>
        </gazebo>

        <joint name="top_drawer_joint" type="prismatic" >
                <axis xyz="1 0 0" />
                <parent link="${parent}" />
                <child link="${prefix}_drawer" />
                <xacro:insert_block name="origin" />
                <limit lower="0.0" upper="${0.95*drawer_size_y}" effort="100" velocity="100" />
        </joint>

        <transmission name="${prefix}_drawer_joint">
                <type>transmission_interface/SimpleTransmission</type>
                <joint name="top_drawer_joint">
                        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
                </joint>
                <actuator name="${prefix}_drawer_joint_motor">
                        <mechanicalReduction>1</mechanicalReduction>
                        <motorTorqueConstant>1</motorTorqueConstant>
                </actuator>
        </transmission>
</xacro:macro>


</robot>