#ifndef MOBILE_BASE_CONTROLLER__MOBILE_BASE_CONTROLLER_HPP_
#define MOBILE_BASE_CONTROLLER__MOBILE_BASE_CONTROLLER_HPP_

// system
#include <limits>
#include <memory>
#include <string>
#include <vector>

#include "controller_interface/chainable_controller_interface.hpp"
#include "realtime_tools/realtime_buffer.h"
#include "std_msgs/msg/float64_multi_array.hpp"
// auto-generated by generate_parameter_library
#include "mobile_base_controller/visibility_control.h"
#include "mobile_base_controller_parameters.hpp"

namespace mobile_base_controller
{
  using DataType = std_msgs::msg::Float64MultiArray;
  class MobileBaseController : public controller_interface::ChainableControllerInterface
  {
   public:
    MOBILE_BASE_CONTROLLER_PUBLIC
    controller_interface::CallbackReturn on_init() override;

    MOBILE_BASE_CONTROLLER_PUBLIC
    controller_interface::InterfaceConfiguration command_interface_configuration() const override;

    MOBILE_BASE_CONTROLLER_PUBLIC
    controller_interface::InterfaceConfiguration state_interface_configuration() const override;

    MOBILE_BASE_CONTROLLER_PUBLIC
    controller_interface::CallbackReturn on_configure(const rclcpp_lifecycle::State& previous_state) override;

    MOBILE_BASE_CONTROLLER_PUBLIC
    controller_interface::CallbackReturn on_activate(const rclcpp_lifecycle::State& previous_state) override;

    MOBILE_BASE_CONTROLLER_PUBLIC
    controller_interface::CallbackReturn on_deactivate(const rclcpp_lifecycle::State& previous_state) override;

    MOBILE_BASE_CONTROLLER_PUBLIC
    bool on_set_chained_mode(bool chained_mode) override;

    MOBILE_BASE_CONTROLLER_PUBLIC
    controller_interface::return_type update_and_write_commands(const rclcpp::Time& time,
                                                                const rclcpp::Duration& period) override;

   protected:
    std::vector<hardware_interface::CommandInterface> on_export_reference_interfaces() override;

    controller_interface::return_type update_reference_from_subscribers(const rclcpp::Time& time,
                                                                        const rclcpp::Duration& period) override;

    std::shared_ptr<ParamListener> param_listener_;
    Params params_;

    // Storing command joint names for interfaces
    std::vector<std::string> command_joint_names_;

    std::string node_name_;

    // Degrees of freedom
    size_t dof_;

    realtime_tools::RealtimeBuffer<std::shared_ptr<DataType>> rt_buffer_ptr_;
    rclcpp::Subscription<DataType>::SharedPtr joints_cmd_sub_;

    std::vector<std::string> reference_interface_names_;

    std::vector<std::string> command_interface_names_;
  };
}   // namespace mobile_base_controller

#endif   // MOBILE_BASE_CONTROLLER__MOBILE_BASE_CONTROLLER_HPP_
