version: '3.9'
# services:
#   hardware_nodes:
#     build: 
#       context: .
#       dockerfile: ../../src/ros2/hardware_nodes/Dockerfile
#     restart: on-failure
#     network_mode: host
#     volumes:
#       # Mount the root folder that contains .git
#       - .:/workspace:cached
#       - ../../src/ros2/hardware_nodes/:/workspace/src/hardware_nodes
#     command: /bin/bash -c "cd /workspace/ && source /opt/ros/${ROS_DISTRO}/setup.bash && colcon build && source install/setup.bash;"

services:
  backend:
    build:
      context: ../../src/web/backend
      dockerfile: Dockerfile
    image: backend:fast_api
    ports:
      - "8000:8000"
    volumes:
      - ./backend/:/workspace/:cached
      - ../../src/web/backend:/workspace/src/:cached
    # command: /bin/sh -c "while sleep 1000; do :; done"
    command: /bin/sh -c "python /workspace/src/main.py"
    
  #evtl mit profiles testen um nur backend oder nur frontend zu starten
  frontend:
    build:
      context: ../../src/web/frontend/react_frontend/
      dockerfile: Dockerfile
    image: frontend:react_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/:/workspace/:cached
      - ../../src/web/frontend/react_frontend:/workspace/src/:cached
    command: /bin/sh -c "serve -s /workspace/src/build"

  hardware_nodes:
    build:
      context: ../../src/ros2/hardware_nodes/
      dockerfile: Dockerfile
    image: hardware:hardware_nodes
    network_mode: "host"
    devices:
      - /dev/robast/robast_can:/dev/robast/robast_can
    volumes:
      - ./hardware_nodes/:/workspace/:cached
      - ./../../src/ros2/hardware_nodes/:/workspace/src/hardware_nodes:cached
      - ./../../src/ros2/communication_interfaces/:/workspace/src/communication_interfaces:cached
      - ./../../libs/:/workspace/libs:cached
    command: /bin/sh -c ". /workspace/src/hardware_nodes/start.sh"
    # command: /bin/sh -c "while sleep 1000; do :; done"

