controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_state_broadcaster:
  ros__parameters:
    interfaces:
      - position
      - velocity
    joints:
      - door_opening_mechanism_joint_y_axis_slide
      - door_opening_mechanism_joint_x_axis_slide
      - door_opening_mechanism_joint_rotating_arm
      - door_opening_mechanism_joint_freely_rotating_hook

forward_velocity_controller:
  ros__parameters:
    joints:
      - door_opening_mechanism_joint_y_axis_slide
      - door_opening_mechanism_joint_x_axis_slide
      - door_opening_mechanism_joint_rotating_arm
      - door_opening_mechanism_joint_freely_rotating_hook
    interface_name: velocity

joint_trajectory_controller:
  ros__parameters:
    joints:
      - door_opening_mechanism_joint_y_axis_slide
      - door_opening_mechanism_joint_x_axis_slide
      - door_opening_mechanism_joint_rotating_arm
      - door_opening_mechanism_joint_freely_rotating_hook

    command_interfaces:
      - velocity

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 200.0 # Defaults to 50
    action_monitor_rate: 20.0 # Defaults to 20

    allow_partial_joints_goal: false # Defaults to false
    open_loop_control: true
    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.01 # Defaults to 0.01
      goal_time: 0.0 # Defaults to 0.0 (start immediately)
