fleet_name: "ROBAST_1"
robot_namspaces: ["rb0","rb1"]

dds_domain: 42
dds_robot_state_topic: "robot_state"
dds_mode_request_topic: "mode_request"                           
dds_path_request_topic: "path_request"
dds_destination_request_topic: "destination_request"

max_dist_to_first_waypoint : 10.0
                            
update_state_frequency: 20.0
publish_state_frequency: 2.0
translation_x: -4.117
translation_y: 27.26
rotation: -0.013
scale: 0.928