max_num_keypoints: 2048
device: 'cpu'
# device: 'cuda'
features_for_matcher:  
visualize: False
weights_for_lightglue:
feuerplan:
normalize_keypoints:
descriptor_dim: 256
nms_radius: 4
detection_threshold: 0.0005
remove_borders: 4
n_layers: 9