bt_navigator:
  ros__parameters:
    use_sim_time: False
    global_frame: robot_map
    robot_base_frame: robot_base_link
    odom_topic: /robotnik_base_control/odom

local_costmap:
  local_costmap:
    ros__parameters:
      global_frame: robot_odom
      robot_base_frame: robot_base_link
      stvl_layer:
        pointcloud:
          topic: /robot/robot_front_rgbd_camera_/depth/color/points
        scan:
          data_type: LaserScan
          topic: /front_laser/scan

global_costmap:
  global_costmap:
    ros__parameters:
      global_frame: robot_map
      robot_base_frame: robot_base_link
      obstacle_layer:
        scan:
          topic: /robot/front_laser/scan
      stvl_layer:
        pointcloud:
          topic: /robot/robot_front_rgbd_camera_/depth/color/points
        scan:
          topic: /robot/front_laser/scan

recoveries_server:
  ros__parameters:
    global_frame: robot_odom
    robot_base_frame: robot_base_link