#ifndef CAN_DB_DEFINES_HPP_
#define CAN_DB_DEFINES_HPP_

namespace robast_can_msgs
{
    #define NUM_OF_CAN_MSGS 2

    #define CAN_ID_DRAWER_USER_ACCESS 0x001
    #define CAN_ID_DRAWER_FEEDBACK 0x002

    #define CAN_DLC_DRAWER_USER_ACCESS 8
    #define CAN_DLC_DRAWER_FEEDBACK 1

    #define CAN_MSG_DRAWER_USER_ACCESS 0
    #define CAN_MSG_DRAWER_FEEDBACK 1

    #define CAN_SIGNAL_DRAWER_CONTROLLER_ID 0
    #define CAN_SIGNAL_OPEN_LOCK_1 1
    #define CAN_SIGNAL_OPEN_LOCK_2 2
    #define CAN_SIGNAL_LED_RED 3
    #define CAN_SIGNAL_LED_GREEN 4
    #define CAN_SIGNAL_LED_BLUE 5
    #define CAN_SIGNAL_LED_BRIGHTNESS 6

    #define CAN_SIGNAL_DRAWER_CONTROLLER_ID_BIT_START 0
    #define CAN_SIGNAL_DRAWER_CONTROLLER_ID_BIT_LENGTH 24
    #define CAN_SIGNAL_OPEN_LOCK_1_BIT_START 24
    #define CAN_SIGNAL_OPEN_LOCK_1_BIT_LENGTH 1
    #define CAN_SIGNAL_OPEN_LOCK_2_BIT_START 25
    #define CAN_SIGNAL_OPEN_LOCK_2_BIT_LENGTH 1
    #define CAN_SIGNAL_LED_RED_BIT_START 26
    #define CAN_SIGNAL_LED_RED_BIT_LENGTH 8
    #define CAN_SIGNAL_LED_GREEN_BIT_START 34
    #define CAN_SIGNAL_LED_GREEN_BIT_LENGTH 8
    #define CAN_SIGNAL_LED_BLUE_BIT_START 42
    #define CAN_SIGNAL_LED_BLUE_BIT_LENGTH 8
    #define CAN_SIGNAL_LED_BRIGHTNESS_BIT_START 50
    #define CAN_SIGNAL_LED_BRIGHTNESS_BIT_LENGTH 58

    #define CAN_SIGNAL_DRAWER_CONTROLLER_ID 0
    #define CAN_SIGNAL_IS_ENDSTOP_SWITCH_1_PUSHED 1
    #define CAN_SIGNAL_IS_LOCK_SWITCH_1_PUSHED 2
    #define CAN_SIGNAL_IS_ENDSTOP_SWITCH_2_PUSHED 3
    #define CAN_SIGNAL_IS_LOCK_SWITCH_2_PUSHED 4

    #define CAN_SIGNAL_DRAWER_CONTROLLER_ID_BIT_START 0
    #define CAN_SIGNAL_DRAWER_CONTROLLER_ID_BIT_LENGTH 24
    #define CAN_SIGNAL_IS_ENDSTOP_SWITCH_1_PUSHED_BIT_START 24
    #define CAN_SIGNAL_IS_ENDSTOP_SWITCH_1_PUSHED_BIT_LENGTH 1
    #define CAN_SIGNAL_IS_LOCK_SWITCH_1_PUSHED_BIT_START 25
    #define CAN_SIGNAL_IS_LOCK_SWITCH_1_PUSHED_BIT_LENGTH 1
    #define CAN_SIGNAL_IS_ENDSTOP_SWITCH_2_PUSHED_BIT_START 26
    #define CAN_SIGNAL_IS_ENDSTOP_SWITCH_2_PUSHED_BIT_LENGTH 1
    #define CAN_SIGNAL_IS_LOCK_SWITCH_2_PUSHED_BIT_START 27
    #define CAN_SIGNAL_IS_LOCK_SWITCH_2_PUSHED_BIT_LENGTH 1

    #define CAN_DATA_CLOSE_LOCK 0
    #define CAN_DATA_OPEN_LOCK 1

    #define CAN_DATA_SWITCH_IS_NOT_PUSHED 0
    #define CAN_DATA_SWITCH_IS_PUSHED 1
}

#endif /* CAN_DB_DEFINES_HPP_ */