# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController


joint_trajectory_controller:
  ros__parameters:
    joints:
      - door_opening_mechanism_joint_y_axis_slide
      - door_opening_mechanism_joint_x_axis_slide
      - door_opening_mechanism_joint_rotating_arm
      - door_opening_mechanism_joint_freely_rotating_hook
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity

    state_publish_rate: 50.0 # Defaults to 50
    action_monitor_rate: 20.0 # Defaults to 20

    gains:
      door_opening_mechanism_joint_y_axis_slide:
        p: 1.0
        i: 0.0
        d: 0.0
        i_clamp: 0.0
        ff_velocity_scale: 10.0
      door_opening_mechanism_joint_x_axis_slide:
        p: 0.0
        i: 0.0
        d: 0.0
        i_clamp: 0.0
        ff_velocity_scale: 10.0
      # door_opening_mechanism_joint_rotating_arm:
      #   p: 10.0
      #   i: 1.0
      #   d: 0.1
      # door_opening_mechanism_joint_freely_rotating_hook:
      #   p: 10.0
      #   i: 1.0
      #   d: 0.1