rb_theron_robot_trajectory_executor:
  ros__parameters:
    joint_names:
      - drawer_1_joint
      - drawer_2_joint
      - drawer_3_joint
      - drawer_4_joint
      - drawer_5_joint
    rate: 200
    follow_joint_trajectory_action: "/drawer_planning_group_controller/follow_joint_trajectory"
