# FLEET CONFIG =================================================================
# RMF Fleet parameters

rmf_fleet:
  name: "deliveryRobot"
  fleet_manager:
    ip: "10.10.13.7"
    port: "8003"
    user: "some_user"
    password: "some_password"
  limits:
    linear: [0.4, 0.2] # velocity, acceleration
    angular: [0.3, 0.35] # velocity, acceleration
  profile: # Robot profile is modelled as a circle
    footprint: 0.25 # radius in m
    vicinity: 0.3 # radius in m
  reversible: False # whether robots in this fleet can reverse
  battery_system:
    voltage: 24.0 # V
    capacity: 40.0 # Ahr
    charging_current: 26.4 # A
  mechanical_system:
    mass: 80.0 # kg
    moment_of_inertia: 20.0 #kgm^2
    friction_coefficient: 0.20
  ambient_system:
    power: 20.0 # W
  tool_system:
    power: 760.0 # W
  recharge_threshold: 0.20 # Battery level below which robots in this fleet will not operate
  recharge_soc: 1.0 # Battery level to which robots in this fleet should be charged up to during recharging tasks
  publish_fleet_state: 1.0 # Hz
  responsive_wait: True
  account_for_battery_drain: True
  max_waypoint_merge_distance: 0.3 # m
  task_capabilities: # Specify the types of RMF Tasks that robots in this fleet are capable of performing
    loop: True
    delivery: True
    clean: False
    finishing_request: "nothing" # [park, charge, nothing]

# DeliveryBot CONFIG =================================================================

robots:
  # Here the user is expected to append the configuration for each robot in the
  # fleet.
  # Configuration for first robot in this fleet
  rb_theron:
    robot_config:
      max_delay: 10.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
    rmf_config:
      robot_state_update_frequency: 1.0 #Hz
      start:
        map_name: "Tiplu"
        # waypoint: "charger_deliverybot1" # Optional
        # orientation: 0.0 # Optional, radians
        waypoint: "printer"
        orientation: 0.0
      charger:
        waypoint: "printer"

# TRANSFORM CONFIG =============================================================
# For computing transforms between Robot and RMF coordinate systems

reference_coordinates:
  # Reference Coordinates for 6OG_bp to reallife

  # rmf:
  #   [
  #     [23.1098, -10.9255],
  #     [20.6076, -8.2368],
  #     [26.4201, -11.0498],
  #     [8.1125, -12.7593],
  #   ]

  # robot: [[0.428, -1.62], [-2, -4.31], [0.423, 1.73], [2.57, -16.8]]
  # Reference Coordinates for 6OG_bp to sim
  rmf:
    [
      [9.2936, -7.6929],
      [18.3853, -11.7025],
      [34.7035, -10.7701],
      [31.3, -12.6039],
    ]

  robot: [[8.28, -0.442], [-0.951, 2.82], [-17.2, 1.96], [-13.6, 3.74]]

  # Reference Coordinates for 6OG_bp to reallife cura
  # rmf:
  #   [
  #     [8.1125, -12.7593],
  #     [8.0814, -6.4185],
  #     [26.4201, -11.0498],
  #     [27.8188, -6.7293],
  #   ]

  # robot: [[-18.2, 10.0], [-16.2, 15.7], [-0.25, 5.25], [2.5, 8.7]]
