# Request
string user_id
string first_name
string last_name
---
# Result
bool successful
string error_message
uint8 nfc_code
communication_interfaces/NfcWriteStatus task_status
---
# Feedback
communication_interfaces/NfcWriteStatus task_status
