# Request
uint8 user_id
---
# Result
bool successful
string error_message
string nfc_code
communication_interfaces/NfcWriteStatus task_status
---
# Feedback
communication_interfaces/NfcWriteStatus task_status
