version: '3.9'

services:
  simulation:
    image: ghcr.io/robast-gmbh/monorepo/simulation:devel-humble
    environment:
      - ROS_DOMAIN_ID=1
      - is_simulation=True
      - config_directory=config_simulation
      - CYCLONEDDS_URI=<?xml version="1.0" encoding="us-ascii"?><CycloneDDS xmlns="https://cdds.io/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://cdds.io/config https://raw.githubusercontent.com/eclipse-cyclonedds/cyclonedds/master/etc/cyclonedds.xsd"><Domain id="any"><General><AllowMulticast>false</AllowMulticast></General><Discovery><ParticipantIndex>auto</ParticipantIndex><Peers><Peer Address="simulation"/><Peer Address="navigation"/><Peer Address="perception"/><Peer Address="hardwarenodes"/></Peers><MaxAutoParticipantIndex>50</MaxAutoParticipantIndex></Discovery><Internal><SocketReceiveBufferSize min="10MB"/></Internal></Domain></CycloneDDS>
      - robot_name=rb_theron
      - init_x=-2.0
      - init_y=0.0
      - init_z=0.0
      - init_yaw=3.14
      - robot=rb_theron
      - prefix=
    volumes:
      - ./simulation/:/workspace/:cached
      - ../../src/ros2/simulation:/workspace/src/simulation:cached
      - ../../src/ros2/robot_description:/workspace/src/robot_description:cached
      - ../../src/ros2/communication_interfaces:/workspace/src/communication_interfaces:cached
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../../src/ros2/dds_configs:/workspace/dds_configs:cached
      - ../../src/robot_backend/:/workspace/src/robot_backend:cached
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports: 
      - "8001:8001"
    
  navigation:
    image: ghcr.io/robast-gmbh/monorepo/navigation:devel
    environment:
      - ROS_DOMAIN_ID=1
      - is_simulation=True
      - config_directory=config_simulation
      - robot_name=rb_theron
      - init_x=0.0
      - init_y=0.0
      - CYCLONEDDS_URI=<?xml version="1.0" encoding="us-ascii"?><CycloneDDS xmlns="https://cdds.io/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://cdds.io/config https://raw.githubusercontent.com/eclipse-cyclonedds/cyclonedds/master/etc/cyclonedds.xsd"><Domain id="any"><General><AllowMulticast>false</AllowMulticast></General><Discovery><ParticipantIndex>auto</ParticipantIndex><Peers><Peer Address="simulation"/><Peer Address="navigation"/><Peer Address="perception"/></Peers><MaxAutoParticipantIndex>50</MaxAutoParticipantIndex></Discovery><Internal><SocketReceiveBufferSize min="10MB"/></Internal></Domain></CycloneDDS>
      - init_z=0.0
      - init_yaw=0.0
    volumes:
      - ./navigation/:/workspace/:cached
      - ../../src/ros2/navigation:/workspace/src/navigation:cached
      - ../../src/ros2/communication_interfaces:/workspace/src/communication_interfaces:cached
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../../src/ros2/dds_configs:/workspace/dds_configs:cached
    command: /bin/sh -c "while sleep 1000; do :; done"

  perception:
    image: ghcr.io/robast-gmbh/monorepo/perception:devel
    environment:
      - CYCLONEDDS_URI=<?xml version="1.0" encoding="us-ascii"?><CycloneDDS xmlns="https://cdds.io/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://cdds.io/config https://raw.githubusercontent.com/eclipse-cyclonedds/cyclonedds/master/etc/cyclonedds.xsd"><Domain id="any"><General><AllowMulticast>false</AllowMulticast></General><Discovery><ParticipantIndex>auto</ParticipantIndex><Peers><Peer Address="simulation"/><Peer Address="navigation"/><Peer Address="perception"/></Peers><MaxAutoParticipantIndex>100</MaxAutoParticipantIndex></Discovery><Internal><SocketReceiveBufferSize min="10MB"/></Internal></Domain></CycloneDDS>
      - ROS_DOMAIN_ID=1
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    volumes:
      - ./perception/:/workspace/:cached
      - ../../src/ros2/perception:/workspace/src/perception:cached
      - /tmp/.X11-unix:/tmp/.X11-unix
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: /bin/sh -c "while sleep 1000; do :; done"

  hardwarenodes:
    image: ghcr.io/robast-gmbh/monorepo/hardware_nodes:devel
    environment:
      - CYCLONEDDS_URI=<?xml version="1.0" encoding="us-ascii"?><CycloneDDS xmlns="https://cdds.io/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://cdds.io/config https://raw.githubusercontent.com/eclipse-cyclonedds/cyclonedds/master/etc/cyclonedds.xsd"><Domain id="any"><General><AllowMulticast>false</AllowMulticast></General><Discovery><ParticipantIndex>auto</ParticipantIndex><Peers><Peer Address="simulation"/><Peer Address="navigation"/><Peer Address="perception"/><Peer Address="hardwarenodes"/></Peers><MaxAutoParticipantIndex>100</MaxAutoParticipantIndex></Discovery><Internal><SocketReceiveBufferSize min="10MB"/></Internal></Domain></CycloneDDS>
      - ROS_DOMAIN_ID=1
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    volumes:
      -  ../../src/ros2/hardware_nodes/:/workspace/src/hardware_nodes:cached
      - ../../src/ros2/error_handling/error_utils/:/workspace/src/error_utils:cached
      - ../../src/ros2/communication_interfaces/:/workspace/src/communication_interfaces:cached
      -  ../../libs/:/workspace/libs:cached
      -  ../../src/ros2/dds_configs:/workspace/dds_configs:cached
      - ./hardware_nodes/:/workspace/:cached
    devices:
      - /dev/robast/robast_nfc:/dev/robast/robast_nfc
    command: /bin/sh -c "while sleep 1000; do :; done"
