version: '3.9'

services:
  simulation:
    build:
      context: .
      dockerfile: ../../src/ros2/simulation/Dockerfile
    image: robast1
    volumes:
      - ./simulation/:/workspace/:cached
      - ../../src/ros2/simulation:/workspace/src/simulation:cached
      - ../../src/ros2/robot_description:/workspace/src/robot_description:cached
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: "host"
    command: /bin/sh -c "while sleep 1000; do :; done"
    
  #evtl mit profiles testen ob man sim nur im simulations modus startet
  navigation:
    build:
      context: .
      dockerfile: ../../src/ros2/navigation/Dockerfile
    image: robast2
    volumes:
      - ./navigation/:/workspace/:cached
      - ../../src/ros2/navigation:/workspace/src/navigation:cached
      - ../../src/ros2/communication_interfaces:/workspace/src/communication_interfaces:cached
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: "host"
    command: /bin/sh -c "while sleep 1000; do :; done"

  # state_publisher:
  #   build:
  #     context: .
  #     dockerfile: ../../src/ros2/simulation/Dockerfile

networks:
  host:
    name: host
    external: true
