sensors:
  - oak_d_sensor
oak_d_sensor:
  filtered_cloud_topic: filtered_cloud
  max_range: 1.5
  max_update_rate: 5.0
  clear_tree_intervall: 10 # specifies the interval in num of updates after which the octomap is cleared
  padding_offset: 0.1
  padding_scale: 1.0
  point_cloud_topic: /back_top_realsense_camera/depth/points
  point_subsample: 1

  # Choose the plugin that should be used to update the octomap.
  ## Available without MoveitPro (and with MoveitPro):
  # sensor_plugin: occupancy_map_monitor/RobastPointCloudOctomapUpdater

  ## Only available with MoveitPro:
  ### The name of the Octomap updater plugin that we are using.
  sensor_plugin: "moveit_studio_plugins/PointCloudServiceOctomapUpdater"
  ### Specifies the topic to listen on for a point cloud. Set to an empty topic to disable.
  point_cloud_service_name: "/point_cloud_service"

# Specifies the resolution at which the octomap is maintained (in meters).
octomap_resolution: 0.02
# Specifies the coordinate frame in which the Octomap representation will be stored.
# Note! When an OccupancyMonitor instance is initialized by the PlanningSceneMonitor,
# this frame parameter will not be used. Instead, the frame defaults to the planning frame.
octomap_frame: "base_link"
