sensors:
  - oak_d_sensor
oak_d_sensor:
  filtered_cloud_topic: filtered_cloud
  max_range: 1.5
  max_update_rate: 5.0
  clear_tree_intervall: 10 # specifies the interval in num of updates after which the octomap is cleared
  padding_offset: 0.1
  padding_scale: 1.0
  point_cloud_topic: /arm/stereo/points
  point_subsample: 1
  sensor_plugin: occupancy_map_monitor/RobastPointCloudOctomapUpdater

# Specifies the resolution at which the octomap is maintained (in meters).
octomap_resolution: 0.05
# Specifies the coordinate frame in which the Octomap representation will be stored.
# Note! When an OccupancyMonitor instance is initialized by the PlanningSceneMonitor,
# this frame parameter will not be used. Instead, the frame defaults to the planning frame.
octomap_frame: "base_link"
