<?xml version="1.0"?>
<robot name="theron_base" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="box_inertia_robot" params="m x y z">
    <inertia  ixx="${m*(y*y+z*z)/12}" ixy = "0" ixz = "0"
              iyy="${m*(x*x+z*z)/12}" iyz = "0"
              izz="${m*(x*x+y*y)/12}" />
  </xacro:macro>

  <xacro:macro name="theron_base" params="prefix publish_bf position_joint_type model_door_opening_mechanism ros2_control_hardware_type_positon_joint hq">

    <xacro:property name="PI" value="3.1415926535897931"/>
    <!-- xacro:property name="wheel_width" value="0.150" / -->

    <!-- BASE FOOTPRINT -->
    <xacro:if value="${publish_bf}">
      <link name="${prefix}base_footprint">
        <visual>
          <origin xyz="0 0 0.01" rpy="0 0 0" />
          <geometry>
            <box size="0.001 0.001 0.001" />
          </geometry>
        </visual>
        <collision>
          <origin xyz="0 0 0.01" rpy="0 0 0" />
          <geometry>
            <box size="0.001 0.001 0.001" />
          </geometry>
        </collision>
      </link>

      <!-- Prismatic position joint -->
      <xacro:if value="${position_joint_type == 'prismatic'}">

        <joint name="position_joint" type="prismatic">
          <axis xyz="-1 0 0" />
          <origin xyz="0 0 0" rpy="0 0 0" />
          <parent link="${prefix}base_footprint"/>
          <child link="${prefix}base_link"/>
          <limit lower="-3.0" upper="3.0" effort="1000" velocity="100" />
        </joint>

      </xacro:if>

      <!-- Planar position joint -->
      <xacro:if value="${position_joint_type == 'planar'}">

        <link name="${prefix}odom">
          <inertial>
            <mass value="0.01" />
            <origin xyz="0.0 0.0 0.0" />
            <xacro:solid_cuboid_inertia m="0.01" w="0.001" h="0.001" d="0.001" />
          </inertial>
          <visual>
            <origin xyz="0 0 0.01" rpy="0 0 0" />
            <geometry>
              <box size="0.001 0.001 0.001" />
            </geometry>
          </visual>
          <collision>
            <origin xyz="0 0 0.01" rpy="0 0 0" />
            <geometry>
              <box size="0.001 0.001 0.001" />
            </geometry>
          </collision>
        </link>

        <joint name="position" type="planar">
          <origin rpy="0 0 0" xyz="0 0 0"/>
          <parent link="${prefix}odom"/>
          <child link="${prefix}base_footprint"/>
        </joint>

        <!-- <joint name="position" type="prismatic">
          <axis xyz="-1 0 0" />
          <origin rpy="0 0 0" xyz="0 0 0"/>
          <parent link="odom"/>
          <child link="${prefix}base_footprint"/>
          <limit lower="-1" upper="1" effort="1000" velocity="100" />
        </joint>         -->

        <joint name="${prefix}base_footprint_joint" type="fixed">
          <origin xyz="0 0 ${wheel_radius - wheel_offset_z}" rpy="0 0 0" />
          <parent link="${prefix}base_footprint"/>
          <child link="${prefix}base_link"/>
        </joint>

        <ros2_control name="position_ros2_control" type="system">
          <hardware>
            <xacro:if value="${ros2_control_hardware_type_positon_joint == 'mock_components'}">
              <plugin>mock_components/GenericSystem</plugin>
              <param name="calculate_dynamics">true</param>
            </xacro:if>
            <xacro:if value="${ros2_control_hardware_type_positon_joint == 'gz_ros2_control'}">
              <xacro:if value="${ros_distro == 'humble'}">
                <plugin>ign_ros2_control_base_movement/IgnBaseMovementSystemHardware</plugin>
                <param name="odom_topic">/diff_drive_base_controller/odom</param>
              </xacro:if>
              <xacro:unless value="${ros_distro == 'humble'}">
                <plugin>gz_ros2_control_base_movement/GzBaseMovementSystemHardware</plugin>
                <param name="odom_topic">/diff_drive_base_controller/odom</param>
              </xacro:unless>
            </xacro:if>
            <xacro:if value="${ros2_control_hardware_type_positon_joint == 'real_life'}">
              <plugin>ros2_control_base_movement/BaseMovementSystemHardware</plugin>
              <param name="odom_topic">/diff_drive_base_controller/odom</param>
            </xacro:if>
          </hardware>
          <!-- Virtual position joint for supporting MoveIt's planar joint type in joint trajectories -->
          <joint name="position/x">
            <param name="initial_position">0.0</param>
            <command_interface name="velocity"/>
            <state_interface name="position"/>
            <state_interface name="velocity"/>
          </joint>
          <joint name="position/y">
            <param name="initial_position">0.0</param>
            <command_interface name="velocity" />
            <state_interface name="position"/>
            <state_interface name="velocity"/>
          </joint>
          <joint name="position/theta">
            <param name="initial_position">0.0</param>
            <command_interface name="velocity" />
            <state_interface name="position"/>
            <state_interface name="velocity"/>
          </joint>

          <!-- Wheel joints used for diff drive controller support -->
          <joint name="joint_left_wheel">
            <command_interface name="velocity"/>
            <state_interface name="position"/>
            <state_interface name="velocity"/>
          </joint>
          <joint name="joint_right_wheel">
            <command_interface name="velocity"/>
            <state_interface name="position"/>
            <state_interface name="velocity"/>
          </joint>
        </ros2_control>

      </xacro:if>

      <!-- Fixed position joint -->
      <xacro:if value="${position_joint_type == 'fixed'}">
        <joint name="${prefix}base_footprint_joint" type="fixed">
          <origin xyz="0 0 ${wheel_radius - wheel_offset_z}" rpy="0 0 0" />
          <parent link="${prefix}base_footprint"/>
          <child link="${prefix}base_link"/>
        </joint>
      </xacro:if>

      <xacro:if value="${model_door_opening_mechanism}">
        <xacro:include filename="$(find rb_theron_description)/urdf/door_opening_mechanism/ros2_control/position_ros2_control.urdf.xacro" />
        <xacro:position_ros2_control 
            ros2_control_hardware_type_positon_joint="${ros2_control_hardware_type_positon_joint}"
            ros_distro="${ros_distro}">
        </xacro:position_ros2_control>
      </xacro:if>

    </xacro:if>

    <!-- BASE_LINK -->
    <link name="${prefix}base_link">
      <inertial>
        <mass value="45" />
        <origin xyz="0.0 0.0 0.0" />
        <xacro:solid_cuboid_inertia m="45" w="0.3275" h="0.2775" d="0.1525" />
      </inertial>
      <visual>
        <!-- <origin xyz="0 0 0" rpy="0 0 0" /> -->
        <xacro:if value="${hq}">
          <geometry>
            <mesh filename="(find rb_theron_description)/meshes/bases/theron_base.stl"/>
          </geometry>
        </xacro:if>
        <xacro:unless value="${hq}">
          <origin xyz="0 0 0.105" rpy="0 0 0" />
          <geometry>
            <box size="0.390 0.240 0.140"/>
          </geometry>
        </xacro:unless>
        <material name="darkgrey">
          <color rgba="0.1 0.1 0.1 1"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0.105" rpy="0 0 0 " />
        <geometry>
          <box size="0.390 0.240 0.140"/>
          <!-- <mesh filename="(find rb_theron_description)/meshes/bases/theron_base.dae"/> -->
        </geometry>
      </collision>
    </link>

    <joint name="${prefix}bottom_sheet_joint" type="fixed">
       <origin rpy="0 0 0" xyz="0 0 0"/>
       <parent link="${prefix}base_link"/>
       <child link="${prefix}bottom_sheet_link"/>
    </joint>

    <link name="${prefix}bottom_sheet_link">
      <inertial>
        <mass value="2.0" />
        <origin xyz="0 0 0" />
	    <xacro:box_inertia_robot m="2" x="0.700" y="0.600" z="0.350"/>
      </inertial>
      <visual>
        <xacro:if value="${hq}">
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
            <mesh filename="$(find rb_theron_description)/meshes/bases/mcq_prototype_bottom_cover.dae"/>
          </geometry>
        </xacro:if>
        <xacro:unless value="${hq}">
          <origin xyz="0 0 0.2" rpy="0 0 0"/>
          <geometry>
            <box size="0.655 0.54 0.02"/>
          </geometry>
        </xacro:unless>
        <material name="darkgrey">
          <color rgba="0.1 0.1 0.1 1"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0.2" rpy="0 0 0" />
        <geometry>
          <box size="0.655 0.54 0.02"/>
          <!-- <mesh filename="$(find rb_theron_description)/meshes/bases/mcq_prototype_bottom_cover.dae"/> -->
        </geometry>
      </collision>
    </link> 
  </xacro:macro>
</robot>
