# list of interim_goals used in the interim_goal_selector node
1:
  x: 7.2
  y: 12.5
  yaw: 3.14
2:
  x: 12.0
  y: 12.3
  yaw: 3.14
3:
  x: 19.7
  y: 12.4
  yaw: 3.14
4:
  x: 23.2
  y: 12.4
  yaw: 3.14