# list of interim_goals used in the interim_goal_selector node
1:
  x: 7.2
  y: 12.5
  yaw: 3.14
2:
  x: 12.0
  y: 12.3
  yaw: 3.14
3:
  x: 19.7
  y: 12.4
  yaw: 3.14
4:
  x: 23.2
  y: 12.4
  yaw: 3.14
5:
  x: 31.4
  y: 12.4
  yaw: 3.14
6:
  x: 8.4
  y: 8.2
  yaw: 3.14
7:
  x: 15.9
  y: 5.0
  yaw: 3.14
8:
  x: 23.1
  y: 5.0
  yaw: 3.14
# Rooms on the other side
9:
  x: 33.7
  y: 12.4
  yaw: 3.14
10:
  x: 39.0
  y: 12.4
  yaw: 3.14