# list of interim_goals used in the interim_goal_selector node
1:
  x: 7.2
  y: 10.6
  yaw: 3.14
2:
  x: 12.0
  y: 10.6
  yaw: 3.14
3:
  x: 19.8
  y: 10.6
  yaw: 3.14
4:
  x: 23.2
  y: 10.6
  yaw: 3.14
5:
  x: 31.4
  y: 10.8
  yaw: 3.14
6:
  x: 8.4
  y: 6.8
  yaw: 3.14
7:
  x: 15.9
  y: 6.4
  yaw: 3.14
8:
  x: 23.1
  y: 6.5
  yaw: 3.14
# Rooms on the other side
9:
  x: 33.7
  y: 10.9
  yaw: 3.14
10:
  x: 39.0
  y: 10.9
  yaw: 3.14