# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    drawer_planning_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

drawer_planning_group_controller:
  ros__parameters:
    joints:
      - drawer_1_joint
      - drawer_2_joint
      - drawer_3_joint
      - drawer_4_joint
      - drawer_5_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity