
  RESTAPI_PORT: 3000
  FLEETMANAGEMENT_ADDRESS: "http://localhost:3002" 
  FLEET_NAME: "ROBAST"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_SERVER: "localhost"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "robast"