/oak:
  ros__parameters:
    camera:
      i_nn_type: spatial
    rgb:
      i_enable_preview: true
      i_keep_preview_aspect_ratio: false
      i_height: 640
      i_width: 640
    nn:
      i_nn_config_path: src/navigation/door_handle_detection/resources/best.json
      i_enable_passthrough: true
      i_enable_passthrough_depth: true
      i_disable_resize: false
    stereo:
      i_subpixel: true