name: Create Multi-Platform Manifest
on:
  workflow_call:
    inputs:
      registry:
        description: 'The registry to push the image to'
        default: 'ghcr.io'
        required: true
        type: string
      repo:
        description: 'The repository to push the image to'
        default: 'robast-gmbh/monorepo'
        required: true
        type: string
      project-name:
        description: 'The project name to push the image to'
        required: true
        type: string
      tag:
        description: 'The tag to push the image to'
        default: 'humble-release'
        required: true
        type: string

jobs:
  create-manifest:
    runs-on: ubuntu-latest
    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Install jq
      run: sudo apt-get update && sudo apt-get install -y jq

    - name: Configure Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Get digest for arm64 image
      id: digest-arm64
      run: |
        digest=$(docker buildx imagetools inspect --raw ${{ inputs.registry }}/${{ inputs.repo }}/${{ inputs.project-name }}:${{ inputs.tag }}-arm64 | jq -r '.manifests[] | select(.platform.architecture == "arm64") | .digest')
        echo "::set-output name=digest::$digest"

    - name: Get digest for amd64 image
      id: digest-amd64
      run: |
        digest=$(docker buildx imagetools inspect --raw ${{ inputs.registry }}/${{ inputs.repo }}/${{ inputs.project-name }}:${{ inputs.tag }}-amd64 | jq -r '.manifests[] | select(.platform.architecture == "amd64") | .digest')
        echo "::set-output name=digest::$digest"            

    - name: Create manifest
      run: |
        docker manifest create ${{ inputs.registry }}/${{ inputs.repo }}/${{ inputs.project-name }}:${{ inputs.tag }} \
        --amend ${{ inputs.registry }}/${{ inputs.repo }}/${{ inputs.project-name }}@${{ steps.digest-arm64.outputs.digest }} \
        --amend ${{ inputs.registry }}/${{ inputs.repo }}/${{ inputs.project-name }}@${{ steps.digest-amd64.outputs.digest }}
        docker manifest push ${{ inputs.registry }}/${{ inputs.repo }}/${{ inputs.project-name }}:${{ inputs.tag }}

