name: Create ROS2 Docker
on:
    workflow_call:
        inputs:
            ros_distro:
                required: true
                type: string
            project_name:
                required: true
                type: string
            tag:
                required: true
                type: string
            target:
                required: false
                type: string
                default: "devel"
            platforms:
                required: false
                type: string
                default: "linux/amd64"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository and submodules
              uses: actions/checkout@v4
              with:
                  fetch-depth: 2

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: configures Docker Buildx to create a builder instance for running the image build.
              uses: docker/setup-buildx-action@v3

            - name:  Build ${{ inputs.project_name}} ${{inputs.tag}} docker
              uses: docker/build-push-action@v6
              with:
                    context: src/ros2/${{ inputs.project_name }}/
                    target: ${{ inputs.target }}
                    platforms: ${{ inputs.platforms }}
                    push: true
                    file: src/ros2/${{ inputs.project_name }}/Dockerfile
                    build-args: GIT_TOKEN=${{ secrets.DOCKER_GIT_TOKEN }}
                    tags: ghcr.io/robast-gmbh/monorepo/${{ inputs.project_name }}:${{ inputs.tag }}-${{inputs.ros_distro}}