name: Create Multi-Platform Manifest
on:
  workflow_call:
    inputs:
      project-name:
        description: 'The project name to push the image to'
        required: true
        type: string
      tag:
        description: 'The tag to push the image to'
        default: 'humble-release'
        required: true
        type: string
      branch-tag:
        description: 'The optional branch tag to push the image to'
        required: false
        type: string

env:
  Registry: ghcr.io
  Repo: robast-gmbh/monorepo        

jobs:
  create-manifest:
    runs-on: ubuntu-latest
    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.Registry }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Install jq
      run: sudo apt-get update && sudo apt-get install -y jq

    - name: Configure Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Get digest for arm64 image
      id: digest-arm64
      run: |
        digest=$(docker buildx imagetools inspect --raw ${{ env.Registry }}/${{ env.Repo }}/${{ inputs.project-name }}:${{ inputs.tag }}-arm64${{ inputs.branch-tag }} | jq -r '.manifests[] | select(.platform.architecture == "arm64") | .digest')
        echo "::set-output name=digest::$digest"

    - name: Get digest for amd64 image
      id: digest-amd64
      run: |
        digest=$(docker buildx imagetools inspect --raw ${{ env.Registry }}/${{ env.Repo }}/${{ inputs.project-name }}:${{ inputs.tag }}-amd64${{ inputs.branch-tag }} | jq -r '.manifests[] | select(.platform.architecture == "amd64") | .digest')
        echo "::set-output name=digest::$digest"            

    - name: Create manifest
      run: |
        docker manifest create ${{ env.Registry }}/${{ env.Repo }}/${{ inputs.project-name }}:${{ inputs.tag }}${{ inputs.branch-tag }} \
        --amend ${{ env.Registry }}/${{ env.Repo }}/${{ inputs.project-name }}@${{ steps.digest-arm64.outputs.digest }} \
        --amend ${{ env.Registry }}/${{ env.Repo }}/${{ inputs.project-name }}@${{ steps.digest-amd64.outputs.digest }}
        docker manifest push ${{ env.Registry }}/${{ env.Repo }}/${{ inputs.project-name }}:${{ inputs.tag }}${{ inputs.branch-tag }}

