name: Create ROS2 Docker
on:
  workflow_call:
    inputs:
      project-name:
        description: 'The project name to push the image to'
        required: true
        type: string
      tag:
        description: 'The tag to push the image to'
        required: true
        type: string
      branch-tag:
        description: 'The optional branch tag to push the image to'
        required: false
        type: string
      target:
        default: "devel"
        required: false
        type: string
      platforms:
        default: "linux/amd64"
        required: false
        type: string
      runner:
        default: "ubuntu-latest"
        required: false
        type: string

env:
  Registry: ghcr.io
  Repo: robast-gmbh/monorepo

jobs:
  build:
    runs-on: ${{ inputs.runner}}
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.Registry}}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: configures Docker Buildx to create a builder instance for running the image build.
      uses: docker/setup-buildx-action@v3

    - name:  Build ${{ inputs.project-name}} ${{inputs.tag}} docker
      uses: docker/build-push-action@v6
      with:
        context: src/ros2/${{ inputs.project-name }}/
        target: ${{ inputs.target }}
        platforms: ${{ inputs.platforms }}
        push: true
        file: src/ros2/${{ inputs.project-name }}/Dockerfile
        build-args: GIT_TOKEN=${{ secrets.DOCKER_GIT_TOKEN }}
        tags: ${{ env.Registry}}/${{ env.Repo}}/${{ inputs.project-name }}:${{ inputs.tag }}${{ inputs.branch-tag }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache