name: Create ROS2 Docker
on:
  workflow_call:
    inputs:
      registry:
        description: 'The registry to push the image to'
        default: 'ghcr.io'
        required: false
        type: string
      repo:
        description: 'The repository to push the image to'
        default: 'robast-gmbh/monorepo'
        required: false
        type: string
      ros_distro:
        default: 'humble'
        required: true
        type: string
      project_name:
        required: true
        type: string
      tag:
        required: true
        type: string
      target:
        default: "devel"
        required: false
        type: string
      platforms:
        default: "linux/amd64"
        required: false
        type: string
      runner:
        default: "ubuntu-latest"
        required: false
        type: string

jobs:
  build:
    runs-on: ${{ inputs.runner}}
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry}}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: configures Docker Buildx to create a builder instance for running the image build.
      uses: docker/setup-buildx-action@v3

    - name:  Build ${{ inputs.project_name}} ${{inputs.tag}} docker
      uses: docker/build-push-action@v6
      with:
        context: src/ros2/${{ inputs.project_name }}/
        target: ${{ inputs.target }}
        platforms: ${{ inputs.platforms }}
        push: true
        file: src/ros2/${{ inputs.project_name }}/Dockerfile
        build-args: GIT_TOKEN=${{ secrets.DOCKER_GIT_TOKEN }}
        tags: ${{ inputs.registry}}/${{ inputs.repo}}/${{ inputs.project_name }}:${{ inputs.tag }}-${{inputs.ros_distro}}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache