name: Create Docker Image Hardware Nodes

#trigger workflow every day at 00:00
on:
  schedule:
    - cron: '0 0 * * 1,5'
  push:
    branches:
        - main
    paths:
        - src/ros2/hardware_nodes/Dockerfile
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      Ros-Distro: humble
      Project-Name: hardware_nodes

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: configures Docker Buildx to create a builder instance for running the image build.
      uses: docker/setup-buildx-action@v1 
    
    - name: Build statemaschine dev docker
      uses: docker/build-push-action@v2
      with:
        context: src/ros2/${{ env.Project-Name }}/
        push: true
        file: src/ros2/${{ env.Project-Name }}/Dockerfile
        tags: |
              ghcr.io/robast-gmbh/monorepo/${{ env.Project-Name }}
        cache-from: type=gha
        cache-to: type=gha,mode=max