name: Create Docker Image debug

#trigger workflow every day at 00:00
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      Ros-Distro: humble
      Project-Name: debug

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: configures Docker Buildx to create a builder instance for running the image build.
      uses: docker/setup-buildx-action@v3 
    
    - name: Build ${{ env.Project-Name }} dev docker
      uses: docker/build-push-action@v6
      with:
        context: bringups/debugging_docker/
        platforms: linux/amd64,linux/arm64/v8
        push: true
        file: bringups/debugging_docker/Dockerfile
        tags: |
              ghcr.io/robast-gmbh/monorepo/${{ env.Project-Name }}
        cache-from: type=gha
        cache-to: type=gha,mode=min
