name: Create Docker Image Simulation

#trigger workflow every day at 00:00
on:
  schedule:
    - cron: '0 0 07 * *'
  push:
    branches:
        - main
    paths:
        - src/ros2/simulation/Dockerfile
  workflow_dispatch:

jobs:
  create_ros2_humble_docker:
      uses: ./.github/workflows/create_ros2_docker.yml
      with:
        ros_distro: humble
        project_name: simulation
        tag: devel
        target: devel
        platforms: linux/amd64
  
  create_ros2_iron_docker:
      uses: ./.github/workflows/create_ros2_docker.yml
      with:
        ros_distro: iron
        project_name: simulation
        tag: devel
        target: devel
        platforms: linux/amd64
  
  create_ros2_jazzy_docker:
      uses: ./.github/workflows/create_ros2_docker.yml
      with:
        ros_distro: jazzy
        project_name: simulation
        tag: devel
        target: devel
        platforms: linux/amd64
