name: Create Docker Image Statemachine

#trigger workflow every day at 00:00
on:
  schedule:
    - cron: '0 0 * * 1'
  push:
    branches:
        - dev/RE-1619
    paths:
        - src/ros2/statemachine/Dockerfile


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      Ros-Distro: humble
      Project-Name: statemachine

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: configures Docker Buildx to create a builder instance for running the image build.
      uses: docker/setup-buildx-action@v2 
    
    - name: Build statemaschine devel docker
      uses: docker/build-push-action@v4
      with:
        context: src/ros2/${{ env.Project-Name }}/
        target: devel
        build-args: GIT_TOKEN=${{ secrets.GITHUB_TOKEN }}
        push: true
        file: src/ros2/${{ env.Project-Name }}/Dockerfile
        tags: ghcr.io/robast-gmbh/monorepo/${{ env.Project-Name }}:devel

    - name: Build statemaschine release docker
      uses: docker/build-push-action@v4
      with:
        context: src/ros2/${{ env.Project-Name }}/
        target: release
        build-args: GIT_TOKEN=${{ secrets.GITHUB_TOKEN }}
        push: true
        file: src/ros2/${{ env.Project-Name }}/Dockerfile
        tags: ghcr.io/robast-gmbh/monorepo/${{ env.Project-Name }}:release
