name: Create Docker Image Statemachine

#trigger workflow every day at 00:00
on:
  schedule:
    - cron: '0 0 07 */2 *'
  push:
    branches:
        - main
    paths:
        - src/ros2/statemachine/Dockerfile
        - src/ros2/statemachine/**
        - src/ros2/communication_interfaces/**
  workflow_dispatch:


jobs:
  create_ros2_devel_docker:
      uses: ./.github/workflows/create_ros2_docker.yml
      with:
        ros_distro: jazzy
        project_name: statemachine
        tag: devel
        target: devel
        platforms: linux/amd64

  create_ros2_release_docker:
      uses: ./.github/workflows/create_ros2_docker.yml
      needs: create_ros2_devel_docker
      with:
        ros_distro: jazzy
        project_name: statemachine
        tag: release
        target: release
        platforms: linux/arm64/v8
      secrets: inherit
