name: Create Docker Image Navigation

#trigger workflow every day at 00:00
on:
  schedule:
    - cron: '0 0 07 * *'
  push:
    branches:
        - main
    paths:
        - src/ros2/navigation/Dockerfile
        - src/ros2/navigation/**
        - src/ros2/dds_configs/*
  pull_request:
    paths:
        - src/ros2/navigation/Dockerfile
        - src/ros2/navigation/**
        - src/ros2/dds_configs/*
  workflow_dispatch:

env:
  Project-Name: navigation

jobs:
  set_output_from_env:
    runs-on: ubuntu-latest
    outputs:
      project-name: ${{ steps.set-project-name.outputs.project-name }}
      branch-tag: ${{ steps.set-branch-tag.outputs.branch-tag }}
    steps:
    - id: set-project-name
      run: echo "project-name=${{ env.Project-Name }}" >> "$GITHUB_OUTPUT"
    - id: set-branch-tag
      run: |
        get_branch_name() {
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "${{ github.head_ref || 'none' }}"
          else
            echo "${{ github.ref_name || 'none' }}"
          fi
        }
    
        branch_name=$(get_branch_name)
    
        if ([ "${{ github.event_name }}" = "push" ] || [ "${{ github.event_name }}" = "workflow_dispatch" ]) && [ "$branch_name" = "main" ]; then
          branch_tag=""
        else
          if [[ $branch_name =~ [0-9] ]]; then
            branch_tag="-RE-$(echo $branch_name | grep -oP '\d{1,5}')"
          else
            branch_tag="-$branch_name"
          fi
        fi
    
        echo "branch-tag=$branch_tag" >> "$GITHUB_OUTPUT"

  create-nav-devel:
    needs: set_output_from_env
    uses: ./.github/workflows/create_ros2_docker.yml
    with:
      project-name: ${{ needs.set_output_from_env.outputs.project-name }}
      tag: devel
      target: devel
      branch-tag: ${{ needs.set_output_from_env.outputs.branch-tag }}
      context: src/ros2/${{ needs.set_output_from_env.outputs.project-name }}/
      file: src/ros2/${{ needs.set_output_from_env.outputs.project-name }}/Dockerfile

  create-nav-release:
    needs: set_output_from_env
    uses: ./.github/workflows/create_ros2_docker.yml
    with:
      project-name: ${{ needs.set_output_from_env.outputs.project-name }}
      tag: release
      target: release
      branch-tag: ${{ needs.set_output_from_env.outputs.branch-tag }}
      context: src/ros2/${{ needs.set_output_from_env.outputs.project-name }}/
      file: src/ros2/${{ needs.set_output_from_env.outputs.project-name }}/Dockerfile