name: Create Docker Image Hardware Nodes

#trigger workflow every day at 00:00
on:
  schedule:
    - cron: '0 0 * * 1'
  push:
    branches:
        - main
    paths:
        - src/ros2/hardware_nodes/Dockerfile
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      Ros-Distro: humble
      Project-Name: hardware_nodes

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build ${{ env.Project-Name }} hagen docker
      uses: docker/build-push-action@v4
      with:
        context: src/ros2/${{ env.Project-Name }}/
        target: hagen
        platforms: linux/amd64,linux/arm64/v8
        build-args: GIT_TOKEN=${{ secrets.DOCKER_GIT_TOKEN }}
        push: true
        file: src/ros2/${{ env.Project-Name }}/Dockerfile
        tags: ghcr.io/robast-gmbh/monorepo/${{ env.Project-Name }}:hagen
