name: Create Docker Image Navigation

#trigger workflow every day at 00:00
on:
  schedule:
    - cron: '0 0 07 * *'
  push:
    branches:
        - main
    paths:
        - src/ros2/navigation/Dockerfile
        - src/ros2/navigation/nav_brinup/config/*
        - src/ros2/navigation/nav_brinup/launch/*
        - src/ros2/dds_configs/*
  workflow_dispatch:

jobs:
  create_ros2_devel_docker:
      uses: ./.github/workflows/create_ros2_docker.yml
      with:
        ros_distro: jazzy
        project_name: navigation
        tag: devel
        target: devel
        platforms: linux/amd64

  create_ros2_release_docker:
      uses: ./.github/workflows/create_ros2_docker.yml
      needs: create_ros2_devel_docker
      with:
        ros_distro: jazzy
        project_name: navigation
        tag: release
        target: release
        platforms: linux/amd64
      secrets: inherit
