name: Create Docker Image fleetmanagement

#trigger workflow every day at 00:00
on:
  push:
    branches:
        - main
    paths:
        - src/ros2/fleet_management/Dockerfile
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      Ros-Distro: humble
      Project-Name: fleet_management

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
  
      - name: configures Docker Buildx to create a builder instance for running the image build.
        uses: docker/setup-buildx-action@v3 
      
      - name: Build ${{ env.Project-Name }} docker
        uses: docker/build-push-action@v6
        with:
          context: src/ros2/${{ env.Project-Name }}/
          push: true
          file: src/ros2/${{ env.Project-Name }}/Dockerfile
          tags: |
                ghcr.io/robast-gmbh/monorepo/${{ env.Project-Name }}
          cache-from: type=gha
          cache-to: type=gha,mode=min
