name: Create Docker Image Hardware Nodes

#trigger workflow every day at 00:00
on:
  schedule:
    - cron: '0 0 07 */2 *'
  push:
    branches:
        - main
    paths:
        - src/ros2/hardware_nodes/Dockerfile
  workflow_dispatch:


jobs:
  create_ros2_devel_docker:
    uses: ./.github/workflows/create_ros2_docker.yml
    with:
      ros_distro: jazzy
      project_name: hardware_nodes
      tag: devel
      target: devel
      platforms: linux/amd64

  create_ros2_release_docker:
    uses: ./.github/workflows/create_ros2_docker.yml
    with:
      ros_distro: jazzy
      project_name: hardware_nodes
      tag: release
      target: release
      platforms: linux/amd64,linux/arm64/v8
      secret: ${{ secrets.DOCKER_GIT_TOKEN }}

  
