name: Create Docker Image Robot Backend
#trigger workflow every day at 00:00
on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      Ros-Distro: humble
      Project-Name: robot_backend

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: configures Docker Buildx to create a builder instance for running the image build.
      uses: docker/setup-buildx-action@v2 
    
    - name: Build ${{ env.Project-Name }} release docker
      uses: docker/build-push-action@v4
      with:
        context: src/ros2/${{ env.Project-Name }}/
        platforms: linux/amd64
        push: true
        file: src/${{ env.Project-Name }}/Dockerfile
        tags: ghcr.io/robast-gmbh/monorepo/${{ env.Project-Name }}:release-${{ env.Ros-Distro }}
