name: Create Docker Image RMF
# TODO remove this file again. just for hagen
#trigger workflow every day at 00:00
on:
  push:
    branches:
        - dev/hagen
    paths:
        - src/ros2/rmf/Dockerfile
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      Ros-Distro: humble
      Project-Name: rmf

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: configures Docker Buildx to create a builder instance for running the image build.
      uses: docker/setup-buildx-action@v2 
    
    - name: Build ${{ env.Project-Name }} hagen docker
      uses: docker/build-push-action@v4
      with:
        context: src/ros2/${{ env.Project-Name }}/
        target: hagen
        build-args: GIT_TOKEN=${{ secrets.DOCKER_GIT_TOKEN }} #TODO @TAlscher find a smarter way then using this token
        push: true
        file: src/ros2/${{ env.Project-Name }}/Dockerfile
        tags: ghcr.io/robast-gmbh/monorepo/${{ env.Project-Name }}:hagen
