name: Flutter Linux Build

# Manual dispatch event
on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Install Flutter
      uses: subosito/flutter-action@v2
      id: flutter-action
      with:
         architecture: x64
    - run: |
        git config --global --add safe.directory /opt/hostedtoolcache/flutter/${{ steps.flutter-action.outputs.CHANNEL }}-${{ steps.flutter-action.outputs.VERSION }}-${{ steps.flutter-action.outputs.ARCHITECTURE }}
        flutter --version

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          curl git unzip xz-utils zip libglu1-mesa \
          clang cmake git ninja-build pkg-config \
          libgtk-3-dev liblzma-dev libstdc++-12-dev \
          libmpv-dev mpv

    - name: Install Flutter dependencies
      working-directory: src/web/frontend/robot_apps_flutter/apps/robot_frontend
      run: flutter pub get

    - name: Build Flutter Linux App
      working-directory: src/web/frontend/robot_apps_flutter/apps/robot_frontend
      run: flutter build linux --release

    - name: Upload Linux Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: linux-build
        path: src/web/frontend/robot_apps_flutter/apps/robot_frontend/build/linux/x64/release/bundle




