name: Flutter Linux Build

on:
  push:
    branches:
        - main
    paths:
        - src/web/frontend/robot_apps_flutter/**
  workflow_dispatch:
env:
  PROJECT_NAME: robot_frontend
  ROBOT_FRONTEND_PATH: src/web/frontend/robot_apps_flutter/apps/robot_frontend
jobs:
  build-linux:
    runs-on: Arm64-Flutter

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Install Flutter
      run: |
        git clone https://github.com/flutter/flutter.git $HOME/development/flutter
        cd $HOME/development/flutter
        git checkout stable
        mkdir -p $HOME/development/flutter/bin/cache
        export PATH=$PATH:$HOME/development/flutter/bin
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          curl git unzip xz-utils zip libglu1-mesa \
          clang cmake git ninja-build pkg-config \
          libgtk-3-dev liblzma-dev libstdc++-12-dev \
          libmpv-dev mpv

    - name: Install Flutter dependencies
      working-directory: $ROBOT_FRONTEND_PATH
      run: |
        export PATH=$PATH:$HOME/development/flutter/bin
        flutter pub get

    - name: Build Flutter Linux App
      working-directory: $ROBOT_FRONTEND_PATH
      run: |
        export PATH=$PATH:$HOME/development/flutter/bin
        flutter build linux --release --target-platform linux-arm64

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    - name: configures Docker Buildx to create a builder instance for running the image build.
      uses: docker/setup-buildx-action@v3

    - name: Build docker
      uses: docker/build-push-action@v6
      with:
            context: $ROBOT_FRONTEND_PATH/
            platforms: linux/arm64
            push: true
            file: $ROBOT_FRONTEND_PATH/Dockerfile
            tags: ghcr.io/robast-gmbh/monorepo/$PROJECT_NAME:release




