name: Flutter Linux Build

# Manual dispatch event
on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: Arm64-Flutter

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Install Flutter
      run: |
        git clone https://github.com/flutter/flutter.git $HOME/development/flutter
        cd $HOME/development/flutter
        git checkout stable
        mkdir -p $HOME/development/flutter/bin/cache
        export PATH=$PATH:$HOME/development/flutter/bin
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          curl git unzip xz-utils zip libglu1-mesa \
          clang cmake git ninja-build pkg-config \
          libgtk-3-dev liblzma-dev libstdc++-12-dev \
          libmpv-dev mpv

    - name: Install Flutter dependencies
      working-directory: src/web/frontend/robot_apps_flutter/apps/robot_frontend
      run: flutter pub get

    - name: Build Flutter Linux App
      working-directory: src/web/frontend/robot_apps_flutter/apps/robot_frontend
      run: flutter build linux --release --target-platform linux-arm64

    - name: Upload Linux Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: linux-build
        path: src/web/frontend/robot_apps_flutter/apps/robot_frontend/build/linux/arm64/release/bundle




