name: PlatformIO CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
    - name: Install g++ compiler
      run: |
        sudo apt install build-essential
    - name: Run Tests
      working-directory: robast_can_msgs/tests
      run: |
        g++ -c tests_main.cpp
        g++ tests_main.o tests_can_db.cpp ../can_helper.cpp -o test_executable -I ../
        ./test_executable