name: Drawer Controller Test
on: 
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - src/Hardware/platformio_libs/**
      - .github/workflows/run_hardware_node_tests.yml
       
jobs:
  test-run-drawer-controller:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
           
    - name: Execute tests 
      working-directory: src/Hardware/platformio_libs
      run: >
          cd $(pwd)/utils &&
          cmake -S . -B build -DBUILD_TESTING=ON &&
          cd build &&
          cmake --build . &&
          ctest

  build-platformio-projects:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v4

    - name: Set up PlatformIO
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install PlatformIO
      run: python -m pip install platformio

    - name: Build PlatformIO Drawer Controller project
      working-directory: project_startups/platformio/Drawer_Controller
      run: platformio run

    - name: Build PlatformIO Partial Drawer Controller project
      working-directory: project_startups/platformio/Partial_Drawer_Controller
      run: platformio run      

