name: PlatformIO CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.SUBMODULE_ACCESS_TOKEN }}
        submodules: 'true'
    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v3
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v3
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Run PlatformIO
      working-directory: Drawer_Controller
      run: pio test -e native
    - name: Install g++ compiler
      run: |
        sudo apt install build-essential
    - name: Build Tests
      working-directory: robast_can_msgs/tests
      run: |
        g++ -std=c++17 -c tests_main.cpp
        g++ -std=c++17 tests_main.o tests_robast_can_msgs.cpp ../can_helper.cpp -o test_executable -I ../    
    - name: Execute Tests
      working-directory: robast_can_msgs/tests
      run: |
        ./test_executable
