name: Drawer Controller Test
on: 
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - src/Hardware/cpp/**
      - .github/workflows/run_hardware_node_tests.yml
       
jobs:
  test-run-drawer-controller:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
          submodules: recursive
           
    - name: Execute tests 
      working-directory: src/Hardware/cpp/libs
      run: >
          cd $(pwd)/utils &&
          cmake -S . -B build -DBUILD_TESTING=ON &&
          cd build &&
          cmake --build . &&
          ctest

