name: Hardware Nodes Test

on:
  push:
    branches:
      - 'main'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
          fetch-depth: 2

    - name: Check if the Docker file was changed 
      shell: pwsh
      # Give an id to the step, so we can reference it later
      id: check_file_changed
      working-directory: src/ros2/hardware_nodes
      run: |
        # Diff HEAD with the previous commit
        $diff = git diff --name-only HEAD^ HEAD

        # Check if a file under docs/ or with the .md extension has changed (added, modified, deleted)
        $SourceDiff = $diff | Where-Object { $_ -match 'dockerfile' }
        $HasDiff = $SourceDiff.Length -gt 0

        # Set the output named "docs_changed"
        Write-Host "::set-output name=docs_changed::$HasDiff"

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build docker if dockerfile changed
      working-directory: src/ros2/hardware_nodes
      if: steps.check_file_changed.outputs.docs_changed == 'true'
      run: |
            docker build . --tag ghcr.io/robast-gmbh/monorepo/hardware_nodes_test
            docker run ghcr.io/robast-gmbh/monorepo/hardware_nodes_test 
            docker push ghcr.io/robast-gmbh/monorepo/hardware_nodes_test 

    - name: Run docker and execute tests
      working-directory: src/ros2/hardware_nodes
      run: docker run -v $(pwd):/workspace/src/hardware_nodes -v $(pwd)/../communication_interfaces:/workspace/src/communication_interfaces -v $(pwd)/../../../libs:/workspace/libs --name hardware_nodes_container ghcr.io/robast-gmbh/monorepo/hardware_nodes_test-latest  /bin/sh -c "cd /workspace/ sudo apt-get update && sudo apt-get upgrade -y; rosdep update; rosdep install --from-paths src --ignore-src -r -y; source install/setup.bash; colcon build --cmake-args '-DCMAKE_BUILD_TYPE=RelWithDebInfo' -Wall -Wextra -Wpedantic; colcon test --event-handler=console_direct+; colcon test-result --all"
   
