name: Statemachine Test

on:
  push:
    branches:
      - dev/RE-836

  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - src/ros2/statemachine/*
      - src/ros2/communication_interfaces/*
      - .github/workflows/*
       
jobs:
  test:

    runs-on: ubuntu-latest
    env:
      Project: statemachine

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
          fetch-depth: 2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build docker
      working-directory: src/ros2/${Project} 
      run: |
            docker build . --tag ghcr.io/robast-gmbh/monorepo/${Project}_test
            docker run ghcr.io/robast-gmbh/monorepo/${Project} 
            docker push ghcr.io/robast-gmbh/monorepo/$Project_test 
    - name: Run docker and execute tests
      working-directory: src/ros2/${Project}
      run: docker run -v $(pwd):/workspace/src/${Project} -v $(pwd)/../communication_interfaces:/workspace/src/communication_interfaces --name ${Project}_container ghcr.io/robast-gmbh/monorepo/${Project}_test  /bin/sh -c "cd /workspace/ sudo apt-get update && sudo apt-get upgrade -y; rosdep update; rosdep install --from-paths src --ignore-src -r -y; source install/setup.bash; colcon build --cmake-args '-DCMAKE_BUILD_TYPE=RelWithDebInfo' -Wall -Wextra -Wpedantic; colcon test --event-handler=console_direct+; colcon test-result --all"
