

name: Hardware Nodes Test

on:
  pull_request:
    types:
      - synchronize
      - opened
    paths:
      - src/ros2/hardware_nodes
       
jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
          fetch-depth: 2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build docker
      working-directory: src/ros2/hardware_nodes 
      run: |
            docker build . --tag ghcr.io/robast-gmbh/monorepo/hardware_nodes_test
            docker run ghcr.io/robast-gmbh/monorepo/hardware_nodes_test 
            docker push ghcr.io/robast-gmbh/monorepo/hardware_nodes_test 
    - name: Run docker and execute tests
      working-directory: src/ros2/hardware_nodes
      run: docker run -v $(pwd):/workspace/src/hardware_nodes -v $(pwd)/../communication_interfaces:/workspace/src/communication_interfaces -v $(pwd)/../../../libs:/workspace/libs --name hardware_nodes_container ghcr.io/robast-gmbh/monorepo/hardware_nodes_test  /bin/sh -c "cd /workspace/ sudo apt-get update && sudo apt-get upgrade -y; rosdep update; rosdep install --from-paths src --ignore-src -r -y; source install/setup.bash; colcon build --cmake-args '-DCMAKE_BUILD_TYPE=RelWithDebInfo' -Wall -Wextra -Wpedantic; colcon test --event-handler=console_direct+; colcon test-result --all"
