name: Statemachine Test

on: 
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - src/ros2/statemachine/**
      - src/ros2/communication_interfaces/**
      - .github/workflows/run_statemachine_test.yml
      - .github/workflows/docker_create_statemachine.yml
       
jobs:
  test-run-statemachine:

    runs-on: ubuntu-latest
    env:
      Project: statemachine

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
          submodules: recursive

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate coverage report
      working-directory: src/ros2/${{ env.Project }}
      run: |
          docker run -v $(pwd):/workspace/src/${{ env.Project }}
          -v $(pwd)/../communication_interfaces:/workspace/src/communication_interfaces
          -v $(pwd)/../error_handling/error_utils:/workspace/src/error_handling/error_utils
          -v $(pwd)/../dds_configs:/workspace/dds_configs
          --name ${{ env.Project }}_container ghcr.io/robast-gmbh/monorepo/${{ env.Project }}:devel
          /bin/sh -c "cd /workspace/ &&
          sudo apt-get update &&
          sudo apt-get upgrade -y &&
          rosdep update && rosdep install --from-paths src --ignore-src -r -y &&
          export CYCLONEDDS_URI=/workspace/dds_configs/cyclone_DDS_github_config.xml &&
          . /robast/humble/setup.sh &&
          colcon build --cmake-args '-DCMAKE_BUILD_TYPE=RelWithDebInfo' -Wall -Wextra -Wpedantic &&
          colcon test --packages-skip behaviourtree_cpp &&
          colcon test-result --all &&
          sudo apt install lcov -y &&
          lcov --directory . --capture --output-file coverage-${{env.Project}}.info &&
          lcov --remove coverage-${{env.Project}}.info '/usr/*' --output-file coverage-${{env.Project}}.info &&
          lcov --list coverage-${{env.Project}}.info"

    - name: Wait for coverage report file
      run: |
          sleep 5
          ls src/ros2/${{ env.Project }}/coverage-${{env.Project}}.info

    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: src/ros2/${{ env.Project }}/coverage-${{env.Project}}.info
