name: Moveit Test

on: 
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - src/ros2/ros2_control/**
      - src/ros2/robot_description/**
      - src/ros2/hardware_nodes/dryve_d1_bridge/**
      - /src/ros2/moveit/**
      - .github/workflows/run_moveit_tests.yml
       
jobs:
  test-run-moveit:

    runs-on: ubuntu-latest
    env:
      Project: moveit
      Ros-Distro: humble

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
          submodules: recursive

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
           
    - name: Run docker and execute tests on humble
      working-directory: src/ros2/${{ env.Project }}
      run: >
          docker run -v $(pwd):/workspace/src/${{ env.Project }} -e GZ_VERSION=fortress
          -v $(pwd)/../hardware_nodes/dryve_d1_bridge:/workspace/src/hardware_nodes/dryve_d1_bridge
          -v $(pwd)/../robot_description:/workspace/src/robot_description
          -v $(pwd)/../ros2_control:/workspace/src/ros2_control
          -v $(pwd)/../utils:/workspace/src/utils
          -v $(pwd)/../dds_configs:/workspace/dds_configs
          -v $(pwd)/../communication_interfaces:/workspace/src/communication_interfaces
          --name ${{ env.Project }}_container ghcr.io/robast-gmbh/monorepo/${{ env.Project }}:devel-humble
          /bin/sh -c "cd /workspace/ &&
          sudo apt-get update &&
          sudo apt-get upgrade -y &&
          rosdep update && rosdep install --from-paths src --ignore-src -r -y &&
          export CYCLONEDDS_URI=/workspace/dds_configs/cyclone_DDS_github_config.xml &&
          . /opt/ros/${{ env.Ros-Distro }}/setup.sh &&
          . /workspace_moveit_task_constructor/install/setup.sh &&
          . /workspace_ros_control/install/setup.sh  &&
          colcon build --cmake-args '-DCMAKE_BUILD_TYPE=RelWithDebInfo' -Wall -Wextra -Wpedantic &&
          colcon test &&
          colcon test-result --all"
