name: Navigation Deploy

on:
  push:
    branches:
      - main
    paths:
    - src/ros2/navigation/**
    - src/ros2/communication_interfaces/**
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
          fetch-depth: 2
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    - name: configures Docker Buildx to create a builder instance for running the image build.
      uses: docker/setup-buildx-action@v1      

    - name: Build and Publish Navigation deploy docker  
      uses: docker/build-push-action@v2
      with:
            context:  src/ros2/navigation/
            push: true
            file:  src/ros2/navigation/deploy.Dockerfile
            tags: |
                  ghcr.io/robast-gmbh/monorepo/navigation_deploy
            cache-from: type=gha
            cache-to: type=gha,mode=max